### ISSUE TITLE
タスク定義の削除時に3回のリトライ上限を超えると変なエラーになる

### ISSUE THREAD

**Issue by kyoh86** [wacul/aws-ecs#28]
https://github.com/wcl48/ai-analyst/issues/3362

```
x Unexpected error in `master-batch-project-progress-preparer-service`.
Traceback (most recent call last):
  File "/app/ecs/deploy.py", line 44, in run
    self.process(deploy, mode)
  File "/app/ecs/deploy.py", line 67, in process
    wait_for_stable(
  File "/app/ecs/deploy.py", line 641, in wait_for_stable
    deregister_task_definition(awsutils, service)
  File "/app/ecs/deploy.py", line 625, in deregister_task_definition
    awsutils.deregister_task_definition(service.origin_task_definition_arn)
  File "/app/aws/__init__.py", line 265, in deregister_task_definition
    return response
UnboundLocalError: local variable 'response' referenced before assignment
```

https://github.com/wacul/aws-ecs/blob/3c08b56aa00f41287a553ede087a4311171b18f0/aws/__init__.py#L249-L265

ここで L265で responseなんてassignされてないよってなってる。

まぁそりゃそうだ。
ここでresponseを返そうとするのはそもそも無理筋だよなぁ。

**Comment by podhmo** [comment]
これくらいならflake8 (pyflakes）で検出できるかも。そういえば見てなかった。

**Comment by podhmo** [comment]
あ、無理か、そこまで頑張って解析はしてくれなかった

**Comment by ito-wacul** [comment]
responseの位置変なの全部直しました。
